### PR TITLE
add angular training

### PR DESCRIPTION
**Pull request by pbauer**
was in orphaned branch angular-training

### CODE REVIEW

**Comment by pbauer** [comment]
@ebrehault There are still a bunch of rst-issues.

Also: I think it should be split in several files.

**Comment by pbauer** [comment]
Here are the rst-issues:

```
angular/angular.rst:871: WARNING: Inline emphasis start-string without end-string.
angular/angular.rst:871: WARNING: Inline emphasis start-string without end-string.
angular/angular.rst:873: WARNING: Definition list ends without a blank line; unexpected unindent.
angular/angular.rst:874: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: angular/angular.rst:1060: (SEVERE/4) Title level inconsistent:

Creating a theme to handle the configuration
++++++++++++++++++++++++++++++++++++++++++++
WARNING: angular/angular.rst:1108: (SEVERE/4) Title level inconsistent:

Pushing the Plone configuration from the Angular project
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
WARNING: angular/angular.rst:1137: (SEVERE/4) Title level inconsistent:

Moving logic in a service
+++++++++++++++++++++++++
WARNING: angular/angular.rst:1140: (SEVERE/4) Title level inconsistent:

Reactive programming with RxJS
++++++++++++++++++++++++++++++
WARNING: angular/angular.rst:1143: (SEVERE/4) Title level inconsistent:

Enabling offline & PWA
++++++++++++++++++++++
WARNING: angular/angular.rst:1148: (SEVERE/4) Title level inconsistent:

SEO and server-side rendering
+++++++++++++++++++++++++++++
```

**Comment by pbauer** [comment]
@ebrehault I'll merge it now. Since the build is greend you can fix the rst-issues later.

**Comment by ebrehault** [comment]
Ok I will.
Thanks.

**Comment by fulv** [comment]
@ebrehault I can work on this over the weekend.

**Comment by ebrehault** [comment]
@fulv oh that would be nice!
By the way, we will have 28 people in our training at Barcelona :)

**Pull request merged**
