### PR TITLE
Improve search form. Add short cut cmd-k for focussing search field.

### PR DESCRIPTION
**Pull request by ksuess**
et alteri

### CODE REVIEW

**Comment by stevepiercy** [comment]
The Netlify preview does not work. I see an error message on the search results page:

"Please activate JavaScript to enable the search functionality."

...even though I have JS enabled. Weird...

I assume this works fine locally and when deployed to the training server, but if not, we can tweak it. I'm OK with merging it.

**Comment by ksuess** [comment]
> The Netlify preview does not work. I see an error message on the search results page:
> 
> "Please activate JavaScript to enable the search functionality."
> 
> ...even though I have JS enabled. Weird...
> 
> I assume this works fine locally and when deployed to the training server, but if not, we can tweak it. I'm OK with merging it.

Well, yes that looks strange. I'll merge and check afterwards. Locally it's fine. And it is more or less the great work of @MAX-786 for plone/documentation.
I rearranged the search options (filter on training) a little bit.

**Comment by stevepiercy** [comment]
I think I see the problem. We need to pin Sphinx similar to docs.

https://github.com/plone/training/actions/runs/4215789631/jobs/7317174173#step:8:1654

**Comment by ksuess** [comment]
Can't the commit in plone/documentation. Where did you fix it there?

BTW As this is not urgent, we could wait for a book theme upgrade. This is obviously in the pipeline.

**Comment by stevepiercy** [comment]
I just made a quick edit.

https://github.com/plone/training/commit/971ff75c7c3426cd82fd0cba7e9e7644274f8001

Per https://github.com/plone/documentation/blob/6-dev/requirements.txt#L2

**Comment by ksuess** [comment]
> I just made a quick edit.
> 
> [971ff75](https://github.com/plone/training/commit/971ff75c7c3426cd82fd0cba7e9e7644274f8001)
> 
> Per https://github.com/plone/documentation/blob/6-dev/requirements.txt#L2

Perfect. Thank you!

**Pull request merged**
