### PR TITLE
Constrain addable types does not work; add stuff from latest bobtempl…

### PR DESCRIPTION
**Pull request by fulv**
…ates; add richtext 'text' content.

### CODE REVIEW

**Comment by fulv** [comment]
Please don't merge yet, I need to fix something.

**Comment by jensens** [comment]
@fulv, fyi: to indicate work in progress you can just add the ``pr wip`` label

**Comment by fulv** [comment]
Thanks!

**Comment by hvelarde** [comment]
@fulv is this PR still valid? it needs a rebase.

**Comment by fulv** [comment]
@hvelarde I have no idea what I was trying to do.  The best I can do at the moment is commit to working on this sometime before ploneconf.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
