### PR TITLE
[WIP] Solr Training

### PR DESCRIPTION
**Pull request by tomgross**
This is the documentation of the one day Solr training.

### CODE REVIEW

**Comment by tomgross** [comment]
This is not finished but I guess it is in a reviewable / mergeable state. All the topics are there but need some refinement
@pbauer @tisto Would you mind to look into it and give me some feedback?
Thanks!

**Comment by pbauer** [comment]
@tomgross when I try to build it locally I get many errors:

```
(training_manual) philip@lightning  ~/workspace/training_manual  ➦ 8240c61  make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.1
making output directory...
Initializing Spelling Checker
WARNING: The config value `linkcheck_timeout' has type `float', defaults to `NoneType.'
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.plone.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 104 source files that are out of date
updating environment: 104 added, 0 changed, 0 removed
reading sources... [100%] trainthetrainer/theory
/Users/philip/workspace/training_manual/mastering_plone/features.rst:87: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/philip/workspace/training_manual/solr-training/how-does-collective-solr-work.rst:75: ERROR: Content block expected for the "code" directive; none found.
/Users/philip/workspace/training_manual/solr-training/setup.rst:306: SEVERE: Title level inconsistent:

Excercise
++++++++++++
/Users/philip/workspace/training_manual/solr-training/solr-alternatives.rst:199: ERROR: Unexpected indentation.
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:153: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 7 supplied.

.. code:: New AND York OR Buenos AND Aires
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:160: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 6 supplied.

.. code:: (New AND York) OR (Buenos Aires)
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:172: ERROR: Content block expected for the "code" directive; none found.
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:176: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 2 supplied.

.. code:: "apache solr"~
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:180: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 2 supplied.

.. code:: "apache solr"~7
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:186: ERROR: Content block expected for the "code" directive; none found.
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:190: ERROR: Content block expected for the "code" directive; none found.
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:203: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: effective:[* TO NOW-3MONTHS]
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:207: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: effective:[* TO NOW/DAY-2YEAR]
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:217: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: Description:[* TO *]
/Users/philip/workspace/training_manual/solr-training/solr-gui.rst:221: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code::  -Description:[* TO *]
/Users/philip/workspace/training_manual/theming/basic.rst:13: WARNING: nonlocal image URI found: http://docs.plone.org/_images/change-logo-in-site-control-panel.png
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/philip/workspace/training_manual/deployment/full.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mastering_plone/development_bucarest.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mastering_plone/grok.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mastering_plone/restapi.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mastering_plone/roadmap.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mastering_plone/sneak.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mastering_plone/timing.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/mosaic.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/plone_training_config/what_vagrant_does.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/rapido.rst:: WARNING: document isn't included in any toctree
/Users/philip/workspace/training_manual/trainthetrainer/index.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
/Users/philip/workspace/training_manual/mastering_plone/buildout_1.rst:92: WARNING: Could not lex literal_block as "ini". Highlighting skipped.
/Users/philip/workspace/training_manual/mastering_plone/buildout_1.rst:233: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
/Users/philip/workspace/training_manual/mastering_plone/buildout_1.rst:269: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
/Users/philip/workspace/training_manual/mastering_plone/eggs1.rst:133: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
/Users/philip/workspace/training_manual/mastering_plone/restapi.rst:50: WARNING: Pygments lexer name u'http-request' is not known
/Users/philip/workspace/training_manual/mastering_plone/restapi.rst:63: WARNING: Pygments lexer name u'http-request' is not known
/Users/philip/workspace/training_manual/mastering_plone/restapi.rst:85: WARNING: Pygments lexer name u'http-request' is not known
/Users/philip/workspace/training_manual/mastering_plone/restapi.rst:345: WARNING: Could not lex literal_block as "html". Highlighting skipped.
/Users/philip/workspace/training_manual/mastering_plone/sneak.rst:45: WARNING: Could not lex literal_block as "cfg". Highlighting skipped.
writing output... [100%] trainthetrainer/theory
generating indices... genindex
writing additional pages... search
copying images... [100%] deployment/haproxy.png
copying downloadable files... [100%] _static/plone_training_config.zip
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 37 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by tomgross** [comment]
@pbauer The caption levels were not consistent and some of the code blocks 	syntactically incorrect. This is fixed now.

**Comment by pbauer** [comment]
@tomgross the errors are gone. A at first glance it loooks great. I suggest we merge it now and do any improvements from there. I had some minor changes (like removing "Indices and tables" from index.rst since it breaks the global navigation) but I cannot commit to the fork... 
Can you rebase and then remove the "WIP", please?

**Comment by tomgross** [comment]
Obsoleted by #213

**Pull request closed without merging**
