### PR TITLE
Update Theming Training for Plone Conference 2017

### PR DESCRIPTION
**Pull request by tmassman**
Lots of fixes and enhancements for the theming  training. I will continue to update the last 3 chapters next week, but it would be helpful if this can already be merged and be available online.

Thanks,
Thomas

### CODE REVIEW

**Comment by svx** [comment]
Can someone else, rebase and merge for some reason I can't get git do it. It keeps complaining,
Thanks !

**Comment by pbauer** [comment]
I'll rebase

**Comment by pbauer** [comment]
Not 100% sur if the file ttw/ttw-advanced-2.rst should be there or not, since rebasing was kinda messy. But not it should be easy to clean up any remaining issues.

**Comment by svx** [comment]
I fixed some links and such, build is green and it is deployed.

**Comment by tmassman** [comment]
Cool, thanks!

**Pull request merged**
