### PR TITLE
Convert all files from reST to MyST

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Comment by stevepiercy** [comment]
I'm going to do everything in this step, except delete the `rst2myst` directory. I want to have a record of the process for my future self.

**Comment by stevepiercy** [comment]
One thing that bit me was that `rst2myst` enables `colon_fence` by default. Specify [`--no-colon-fence`](https://rst-to-myst.readthedocs.io/en/latest/cli.html?highlight=colon-fence#rst2myst-convert) to override the default. I don't know why they did that.

There is a total of 351 files to convert.

**Comment by stevepiercy** [comment]
Please take a look at this [specific commit and its message](https://github.com/plone/training/pull/515/commits/1cee91ac25569a1d1ad4569f7336e2058aa61062). This might save y'all some pain and suffering when you edit MyST.

**Comment by stevepiercy** [comment]
Here are the remaining steps to perform, after this PR is merged.

- In `conf.py` remove `rst2myst/training/**` from `exclude_patterns`.
- Uninstall `rst-to-myst`.

  ```shell
  pip uninstall "rst-to-myst[sphinx]"
  ```

- Delete the directory `rst2myst`.

**Review by ksuess — APPROVED** [review]
This looks fine for me. I will take this as a base for applying the theme, adding some theme specific fixes. It would be good not to add further changes to this.

**Comment by stevepiercy** [comment]
@ksuess in Discord you said wait until we can talk before merging this PR, but you approved it. I will wait until I hear back from you.

**Comment by stevepiercy** [comment]
DO NOT MERGE!

Awaiting other PRs to merge to this PR, before merging this PR to master.

- [ ] #516 
- [ ] Enhance search (#TBD)

See also #506 for complete checklist.

**Pull request merged**
