### PR TITLE
Update 6.rst

### PR DESCRIPTION
**Pull request by staeff**
Changes in code that were done during the training in ploneconf 2017

### CODE REVIEW

**Comment by svx** [comment]
@frapell Can you review and merge if OK ?

**Comment by svx** [comment]
@staeff please add a changelog entry :)

**Comment by svx** [comment]
@staeff Thanks !!!

**Comment by staeff** [comment]
@svx yes, i will change it. And a few things more after the lunch break.

**Comment by staeff** [comment]
@svx @frapell - from my site this is ready for review and more feedback or merge if everything looks fine

**Comment by svx** [comment]
LGTM ! @frapell ?

**Comment by frapell** [comment]
@staeff Thanks! :D

**Pull request merged**
