### PR TITLE
Updating the react training

### PR DESCRIPTION
**Pull request by iFlameing**
This pr updated the react training and it uses the latest create-react-app version, react-router-dom, and uses hooks for the training app.

### CODE REVIEW

**Comment by stevepiercy** [comment]
I'll review this in the next day or two, but in the meanwhile, would you please populate the training with relevant metadata information? See https://training.plone.org/5/contributing/authors.html#html-and-open-graph-metadata

**Comment by iFlameing** [comment]
@stevepiercy  I already have a repo with all the exercises in a separate branch. And Final code in the main branch. Here is the link https://github.com/iFlameing/plone-react-training. I need to update the readme though.

**Comment by stevepiercy** [comment]
> @stevepiercy I already have a repo with all the exercises in a separate branch. And Final code in the main branch. Here is the link https://github.com/iFlameing/plone-react-training. I need to update the readme though.

I suggest to add the link in `intro.md` as well.

Also please consider the pattern established in Mastering Plone with its sidebars. This training also uses separate branches for each step with code examples. When I took the training, being able to copy-paste the git command to checkout the branches was super helpful. Example: https://training.plone.org/5/mastering-plone/volto_overrides.html

**Comment by iFlameing** [comment]
@stevepiercy I added the metadata for all pages and also added the GitHub link to the intro.md.

**Pull request merged**
