### PR TITLE
Add improvements about Plone 4 training

### PR DESCRIPTION
**Pull request by macagua**
- Fixed some gettext files errors.

- Updated Gettext files.

- Updated Integration with Transifex https://www.transifex.com/plone/plone4-training/

- Updated Spanish translation files.

### CODE REVIEW

**Comment by pbauer** [comment]
@macagua feel free to merge this yourself when it'ready. Please note that the travis-build will always fails when you use a fork, you might want to use a branch instead. 
We're no longer maintaining the Plone 4 training since it is helplessly behind the Plone 5 version and does not contain any of the additional trainings that are on https://training.plone.org/5/

**Comment by pbauer** [comment]
Also I strongly believe that new developers should learn (and work with) Plone 5 and not Plone 4. I consider working with legacy-code a job for advanced developers.

**Comment by macagua** [comment]
@pbauer thanks you for response!

I made a fork for create a pull request following the contributing guide:

- Plone 4 https://training.plone.org/4/about.html#contributing

But should this new procedure, should be be reflected in the contribution guide for Plone 4 and Plone 5?, right?

- Plone 5 https://training.plone.org/5/mastering_plone/about_mastering.html#contributing

If I use a branch to add new improvements about the docs, then I a create a new branch for example plone4_new_feature, add the new improvements and merge it fron the plone4_new_feature branch to plone4 branch, right?

**Comment by macagua** [comment]
@pbauer About promoting the training of Plone 5 over Plone 4, I agree with you, only that since 2012, we have maintained the translation of Plone 4 from Conectivo R.L. (my company), it was time to share it with the community. Check out the following link:

https://www.transifex.com/plone/plone4-training/translate/#es

In addition the work of the translations of the training of Plone 4, is reusable to feed the minorities of translation of the version of Plone 5 in the platform Transifex.

https://www.transifex.com/plone/plone5-training/translate/#es

Because the translations made for the Plone 4 version are suggested as Plone's LiveSearch functionality, which recommends which element matched your search criteria including a percentage of accuracy, well these previous translations appear as a suggested translation previously performed, This streamlines translation processes, as well as standardizing the terms used for translation.

Also, we (some Plonistas from Venezuela) started the Spanihs translation of Plone 5 training resources, based on the translations made for Plone 4 training resources, I hope to make a pull request with new translations in this case for Plone 5.

**Pull request merged**
