### PR TITLE
Replace backend and frontend logos in "Mastering Plone Development"

### PR DESCRIPTION
**Pull request by ksuess**

### CODE REVIEW

**Comment by stevepiercy** [comment]
Please rebase this branch on `main` and `git push --force` to make it easier to review. Thank you!

**Comment by ksuess** [comment]
I am still not happy with the sidebars: It's up to three times mentioning 'frontend' or 'backend'.
But a title of a sidebar is recommended. 
Any opinions? Or stay with this for now?

23__Volto_View_Components__A_Default_View_for__Talk__–_Mastering_Plone_6_Development_—_Plone_Training_2021_documentation-2

**Comment by stevepiercy** [comment]
> I am still not happy with the sidebars: It's up to three times mentioning 'frontend' or 'backend'.

I would remove the logo. We have the Plone logo already on the left navigation. I agree three instances of "frontend" is one too many. I like a text heading in a sidebar because it gives context and purpose. I'm OK with words in headings being repeated in narrative text.

**Comment by stevepiercy** [comment]
I think it looks fine with or without duplicate Plone logos, and I prefer a single Plone logo.

## Single Plone Logo

Screen Shot 2021-09-16 at 11 42 27 AM

## Duplicate Plone Logo

Screen Shot 2021-09-16 at 11 42 36 AM

Either way, I approve this PR.

**Review by stevepiercy — APPROVED** [review]

**Pull request merged**
