### PR TITLE
Use correct git checkout zpt

### PR DESCRIPTION
**Pull request by stevepiercy**
@pbauer or other to confirm

### CODE REVIEW

**Comment by tschorr** [comment]
#314 is related.

**Comment by tschorr** [comment]
I think we rather have to create the `views_1` tag in the `ploneconf.site` package.

**Comment by stevepiercy** [comment]
@tschorr agreed. I think that's a better way.

**Comment by tschorr** [comment]
Closing in favor of #314 and https://github.com/collective/ploneconf.site/pull/1

**Pull request closed without merging**
