### PR TITLE
about Mastering Plone Development Training and missing credit

### PR DESCRIPTION
**Pull request by ksuess**

### CODE REVIEW

**Comment by jensens** [comment]
+1

Additionally I would put the names in alphabetical order (and add a statement about this on top of the list).
Please ensure to have each sentence on its own line (doc-guidelines/translatability).

**Comment by ksuess** [comment]
> Additionally I would put the names in alphabetical order by last name (and add a statement about this on top of the list).

Are you kidding me? 
My contribution on training Volto app code is completely erased, commits authoring wiped out, contributers list empty: https://github.com/collective/volto-ploneconf.
The conference is three month gone and the master of plone has time to twitter destructive posts but no time to mention me with one word in the training documentation or care for my pull request taking care of myself. 

No, I do not push myself to the end of the list!

**Comment by jensens** [comment]
LOL ok, I am very sorry, I missed that. I have no better Idea how to sort/weight? Number of contributions? Well, just keep it as is, it was probably not well thought.

**Comment by jensens** [comment]
Merged. 

Btw. my personal opinion: Persons should be named as here in a list of contributors, not as before in the text. 
Companies should get contribution as sponsors at plone.org, nowhere else. I.e. I as Klein & PArtner and we as the BlueDynamics Alliance as a whole did a lot for Plone, but I never put my name or BDA in something core related. This is different for add-ons. 

We may want to refine what sponsorship means (like not money-only) but that's a separate discussion.

**Comment by stevepiercy** [comment]
> Additionally I would put the names in alphabetical order by last name (and add a statement about this on top of the list).

That would be culturally exclusive to those that do not use a last name or have multiple last names.

**Comment by jensens** [comment]
Indeed, not well thought as I said. I am curious about a fair, inclusive solution here.

**Pull request merged**
