### PR TITLE
Update README.rst to refer to how to build the docs locally.

### LINKED ISSUE #237: How to get started for contributing?
I'd like to help on improving the training docs, but there are no instructions in this repo for getting started, including (but not limited to):

1. [x] [How to contribute](https://github.com/blog/1184-contributing-guidelines) See #238
1. [x] Installation requirements
1. [x] How to build the docs and verify locally before making a PR

Perhaps some stuff from [Pyramid](https://github.com/Pylons/pyramid) could be useful?

### PR DESCRIPTION
**Pull request by stevepiercy**
- Closes #237

### CODE REVIEW

**Comment by svx** [comment]
Hold on, do not merge !, I will fix that, once for all !

**Comment by svx** [comment]
OK, this improves the README, please note, its is still not 100% conform with our guide lines, but at least 98%.
I did not created a docs folder, since I wanted to avoid to add info like building locally in different places.

IMHO, for now this is OK.
There may be changes in the future, till I really would like to change the whole structure of the training to improve it, but this is for later and needs first some thinking and talking :)

**Comment by stevepiercy** [comment]
This is a vast improvement.

Are [these the guidelines](http://docs.plone.org/about/index.html) of which you speak? Perhaps add that to the README, too?

**Comment by svx** [comment]
@pbauer do you have a minute to review and merge, I do not want to merge my own PR :)

**Comment by svx** [comment]
Upps, yeah you're right, fixed !

**Pull request merged**
