### PR TITLE
Added the missing command

### LINKED ISSUE #714: Missing Command during setting up volto
There is a **missing Command** in the volto setup training documentation

image

In the first part after the `cd my-volto-app` command, there should be a `yarn install` command before the `yarn start` command.
This will be a bit confusing for the new people who are not experienced enough.

So I guess it will be just better to add that command

### PR DESCRIPTION
**Pull request by SaiRev0**
Added the missing `yarn install` command in the volto training docs Closes #714

### CODE REVIEW

**Comment by stevepiercy** [comment]
I think you missed this: https://training.plone.org/volto/bootstrap.html#installing-prerequisites

> 3.2. Installing Prerequisites
> First [Install nvm (NodeJS version manager)](https://6.docs.plone.org/volto/getting-started/install.html#frontend-getting-started-install-nvm-label).
>
> [Install Yarn](https://6.docs.plone.org/volto/getting-started/install.html#frontend-getting-started-yarn-label).

But even that is out of date. The Training should instead point to installing pre-requisites (https://6.docs.plone.org/install/install-from-packages.html#pre-requisites-for-installation) and remove all of its steps that our out of date.

We really need to purge old installation instructions, and use the authoritative source in the Plone 6 Documentation.

**Comment by wesleybl** [comment]
@SaiRev0 when you run `yo @plone/volto`, it already runs `yarn install`.

**Comment by SaiRev0** [comment]
> @SaiRev0 when you run `yo @plone/volto`, it already runs `yarn install`.

I guess there is some error then, I m facing this issue 

image

**Comment by stevepiercy** [comment]
@SaiRev0 https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors

**Comment by stevepiercy** [comment]
@SaiRev0 @wesleybl I created two issues:

- https://github.com/plone/volto/issues/4440
- https://github.com/plone/training/issues/716

**Pull request closed without merging**
