### PR TITLE
Solr docs review

### PR DESCRIPTION
**Pull request by gforcada**
Mostly just rst syntax and some typos here and there

### CODE REVIEW

**Comment by tomgross** [comment]
@gforcada Thanks for the work. I'll merge if travis passes.

**Comment by gforcada** [comment]
They seem to be pretty much unrelated to my changes... @svx any idea of what's the specific error to be fixed? I didn't really understand travis output (ok I'm falling sleep so that could be part of the reason as well)

**Comment by svx** [comment]
@gforcada 

```
build finished with problems, 34 warnings.

make: *** [linkcheck] Error 1
```

This may be unrelated to your changes, but there is a failing test, for a link, so this needs to be checked, is the link broken ? Is/was is a timeout ?

**Comment by svx** [comment]
@gforcada to be exact:

line   55) broken    http://jslinterrors.com/ - [Errno 104] Connection reset by peer

:)

**Comment by svx** [comment]
@gforcada 

Travis has connection problems so it seems, it is giving lots of messages about broken links and if I check them fro hand there are working...

Not the first time we have that, it is really time to move to something more reliable :)

**Comment by svx** [comment]
actually : jslinterrors.com is really not reachable :)

**Comment by gforcada** [comment]
@tomgross tests finally green!

@svx I'm looking forward to this setup 2.0. I had to rerun the test several times as sourceforge.net was timing out...

**Pull request merged**
