### PR TITLE
mixedfield: a datagrid field / widget for Plone 6

### PR DESCRIPTION
**Pull request by ksuess**
…ct-widget

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by sneridagh** [comment]
@ksuess I pushed these days an small but (I think) important micro-feature:
https://github.com/plone/plone.schema/pull/11
https://github.com/plone/plone.restapi/pull/1091

so now we will be able to do:

```
       mixed_field = JSONField(
             # datagrid, mixedfield, field, Plone, json, frontend, Volto
             title=u'Mixedfield: datagrid field for Plone',
             required=False,
             schema=MIXEDFIELD_SCHEMA,
             default={"items": []},
             missing_value={"items": []},
             widget="my_datagrid_widget"
             )
```

then in the config:

```
config.widgets.widgets. my_datagrid_widget = MyDatagridWidget
```

This is important so we do not override field "ids" (which is a kid of a workaround for widgets that do not have the ability to state its widget, or we are not able to infer a proper one), but assigning a proper widget.

**Comment by sneridagh** [comment]
From plone.schema = 1.3.0
and (upcoming, not merged yet) plone.restapi release

**Comment by sneridagh** [comment]
plone.restapi supporting this: https://pypi.org/project/plone.restapi 7.3.0

**Comment by sneridagh** [comment]
@ksuess It would be great if we could have some narrative docs about this in Volto docs as well! "How to use Volto widgets in DX content types". What do you think?

Also, preparing this:
https://github.com/plone/volto/pull/2294

So we will have the full story in Volto core now. :)

**Comment by ksuess** [comment]
@sneridagh, great that you instantaneous could take the time to enhance the JSONField / datagrid topic. This should be documented also in Volto official documentation, yes. I would love to contribute, but please give me some days, I'm working on 17 construction sites.

**Comment by sneridagh** [comment]
@ksuess well, not instantaneous, it's been in the back of my head since long. The current shape of Plone widget serialisation is quite a mess, the use cases and implementations seems to be infinite, I sweat blood back in the day when I wrote the Widget extensibility story. Coincidentally, we had that same requirement in one of our projects, in fact, we did it so far using your approach! So I spent some time investigating if we could have a better story and came up with this. 

Thanks for taking time investigating this subject and for writing this for the training.

**Comment by ksuess** [comment]
I am struggling with the first sentence. Feedback is welcome.

*The mixedfield empowers your user to create a list of arrays of mixed value types.*

And of course the complete text is open for feedback. Thanks in advance.

**Comment by sneridagh** [comment]
Looks awesome!

My 5 cents on the sentence, but no special strong opinion on it:
The mixedfield empowers your user to create a list of objects of mixed value types sharing the same schema.

Not very inspired this evening either 😅

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
