### PR TITLE
Add infos for node lts support

### LINKED ISSUE #687: Plone Deployment macOS tips
zcsh on macOS 10.15 requires that for nvm commands, its options with glob characters `*` be quoted.

https://training.plone.org/plone-deployment/setup.html#node-and-node-tools

```
nvm install lts/*
nvm alias default lts/*
```

Should be:

```
nvm install 'lts/*'
nvm alias default 'lts/*'
```

### PR DESCRIPTION
**Pull request by loechel**
a proposal to fix #687 and #688

### CODE REVIEW

**Review by jensens — APPROVED** [review]
Yes, this clarifies it.

**Comment by loechel** [comment]
@stevepiercy feel free to merge, if you are ok with these changes

**Comment by stevepiercy** [comment]
Thanks, @loechel, I pushed some English grammar fixes. This is very helpful. Merging after green.

**Comment by ksuess** [comment]
Can we please next time make sphinx configuration changes in different PRs, @stevepiercy 
Changes like "Show TODO directives." could need some action for authors.

**Comment by stevepiercy** [comment]
@ksuess `{todo}` directives they should be published. It shows that work needs to be done.  If we don't show them, it could mislead the user to think that everything is OK, and that would be much worse.

If instead the author intends a private comment, then they should use `% my-comment` or `% TODO: something for the author only` as that never shows and does not indicate future work is needed in a public way.

**Comment by ksuess** [comment]
> @ksuess `{todo}` directives should be published. It shows that work needs to be done. If we don't show them, it could mislead the user to think that everything is OK, and that would be much worse.
> 
> If instead the author intends a private comment, then they should use `% my-comment` or `% TODO: something for the author only` as that never shows and does not indicate future work is needed in a public way.

A sphinx configuration change is off topic here. 
This change needs action and therefore should next time be visible as a separate PR.

**Pull request merged**
