### PR TITLE
Anatomy chapter: editing while reading

### PR DESCRIPTION
**Pull request by tschorr**

### CODE REVIEW

**Comment by pbauer** [comment]
please commit these small changes directly to master

**Comment by tschorr** [comment]
> please commit these small changes directly to master

ok will do that in the future.

**Comment by svx** [comment]
Wait a second, please !

Please make sure that your changes are following the style-guide(s) and please build a HTML version locally to see how your changes looks like.
(OK this may be not needed if you fix a typo).

I understand that you want to get the stuff into the training asap, but please, please make sure that the quality is not decreasing !!!

All of you training writers/teachers are awesome !!!
But please do not forget, some people invested a lot of effort and time in helping improving the all over quality by fixing, style, wording and format issues, too !

Please be **careful** with merging straight into master, if you have doubts, not sure or would like to have more eyes checking, please **open** a pull request !

Thanks !

**Comment by tschorr** [comment]
ok will do that in the future ;-)

**Comment by svx** [comment]
Thanks !!! :)

**Pull request merged**
