### PR TITLE
Fix some rst issues

### PR DESCRIPTION
**Pull request by fulv**
I can split this into separate chapters tomorrow.

After I fixed the previous rst issues, these new ones cropped up.  I have no idea what they mean, since the output is highlighted just fine.

```
angular/angular.rst:315: WARNING: Could not lex literal_block as "html". Highlighting skipped.
angular/angular.rst:338: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:455: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:743: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.
angular/angular.rst:800: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.
angular/angular.rst:820: WARNING: Could not lex literal_block as "css". Highlighting skipped.
angular/angular.rst:1016: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:1165: WARNING: Could not lex literal_block as "json". Highlighting skipped.
```

### CODE REVIEW

**Comment by svx** [comment]
I guess this has partly to do with not valid html, json and so on.

For example I did a test with the latest warning: *angular/angular.rst:1165: WARNING*

Testing this as json in my editor gives me lint warnings and online, too.

Sphinx does not know about the rest and is literal on testing this lines.

angular-jsonlint

Also, there is caution needed with things like
...

(three dots as line replacement)

Quite often this gives errors/warnings because sphinx/pygments and/or linter are not understanding this.

With the last couple of releases of Sohinx and pygments, they got more 'picky' and giving now errors/warnings.

Which is IMHO great !

I experienced the same with the Solr training, I had to fix quite a lot of the code examples.

Even if the code is right in the first place, sometimes by 'using just parts' as examples it can turn to this.

**Comment by fulv** [comment]
Thanks, good to know.

Do you know if `.. code-block:: scss` is understood by sphinx?

**Comment by svx** [comment]
@fulv it is supported by Pygments:

```
class pygments.lexers.css.ScssLexer
Short names: scss
*.scss
text/x-scss
```

For SCSS stylesheets.

According to that it should work.
Personally I never used it so far, so I can't say more about it.

**Comment by fulv** [comment]
Ok, I've narrowed down the scss issues to the use of variables, such as `$blue` and `$lightgrey`.  Those are defined in the file `variables.scss`, which of course does not exist in the docs because the trainees are supposed to create them in the angular app source tree themselves.  Does anybody know how to make sphinx ignore variables?

**Comment by svx** [comment]
Or can these variables "faked" ?
If they can be "faked" we could set these "fakes" in the conf.py.

TestTheDocs is doing that for non existing lexer, it is dirty but it works.

**Comment by fulv** [comment]
Is there an example for how to "fake" variables?

**Comment by fulv** [comment]
These are the current warnings, and I've investigated all of them (see below):

```
angular/angular.rst:338: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:456: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:744: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.
angular/angular.rst:801: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.
angular/angular.rst:821: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
angular/angular.rst:1017: WARNING: Could not lex literal_block as "scss". Highlighting skipped.
```

`angular/angular.rst:338: WARNING: Could not lex literal_block as "scss". Highlighting skipped.`
This one is uniquely because of the `$blue` and `$lightgrey` variables.


`angular/angular.rst:456: WARNING: Could not lex literal_block as "scss". Highlighting skipped.`
Due to `$blue` variable.

`angular/angular.rst:744: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.`
This one is because it doesn't like square brackets inside double curly brackets:  `{{ news[current].title }}`

`angular/angular.rst:801: WARNING: Could not lex literal_block as "html+ng2". Highlighting skipped.`
This one is because it doesn't like the `@` sign inside square brackets:
`<div *ngFor="let item of news" class="slide" [@flyInOut]="item.state">`

`angular/angular.rst:821: WARNING: Could not lex literal_block as "scss". Highlighting skipped.`
This one is because it doesn't like the `%` sign, which is silly, e.g. `font-size: 120%` or `width: 100%`, or `top: 60%`, etc.  Also, there is a `$blue` variable.

`angular/angular.rst:1017: WARNING: Could not lex literal_block as "scss". Highlighting skipped.`
This one is because of the `%` sign in `font-size: 130%`.


What are we going to do about these issues?

**Comment by stevepiercy** [comment]
SCSS Pygments lexer has an issue report for both `$` and `%`:
https://bitbucket.org/birkenfeld/pygments-main/issues/1096/scss-variable-not-detected-in-attribute

**Comment by fulv** [comment]
Thanks @stevepiercy.
I notice that issue was opened in 2015 👎

**Pull request merged**
