### PR TITLE
how to install/compile

### PR DESCRIPTION
**Pull request by thet**
this wasn't documented but isn't plain obvious.

@pbauer what's the process of contributing? all via pull requests?

### CODE REVIEW

**Comment by pbauer** [comment]
That is doumented in http://training.plone.org/5/about.html#building-the-documentation-locally

**Comment by thet** [comment]
I knew, this was documented, but I didn't find it! this info is a bit hidden, did expect somethin like INSTALL.rst or being documented in README.rst.
Can be closed then...

**Comment by svx** [comment]
@thet I see potential problems with this line:

To compile this training documentation to html, pdf or other formats, do this::

If I read the as user, I get the idea that I can compile the training docs into pdf, which is not the case with the current setup, in order to be able to do that, you need to change the conf.py.

See this link:

http://sphinx-doc.org/builders.html#builders

saying you have to add: rst2pdf.pdfbuilder to extensions. 

So maybe it would be better to make this clear and remove this part: , pdf or other formats, ?

**Comment by pbauer** [comment]
Building the documentation locally is only really useful for trainers, everyone else should just use the website.

**Comment by thet** [comment]
@sven, we can keep this closed.

**Pull request closed without merging**
