### PR TITLE
Updated Trainings Docs

### PR DESCRIPTION
**Pull request by Vivek-04022001**
Description: I enhanced the language flow in the paragraph, making it easier to comprehend. The previous version was challenging to understand, but the revised version is now more accessible and user-friendly. I, Vivek Kumar, agree to have this contribution published under the Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.

### CODE REVIEW

**Comment by ksuess** [comment]
I appreciate that you looked into this training chapter so detailed. Thanks for the feedback. But I do not agree with your suggestions. It's necessary to use the vocabulary like default view, component, create, contain, etc.. I'll consider your thoughts in the upcoming overhaul.

**Comment by Vivek-04022001** [comment]
Thank you, @ksuess, for your corrections. As a new contributor to Plone, I'm committed to being an active member of this community and learning from experienced mentors. Presently, I've been closely connected with @stevepiercy, who has been guiding me on how to contribute effectively to an open-source organization like Plone. I've gained valuable insights from his mentorship.

I have a minor question. As a newcomer to this organization, I spend a significant amount of time reading documentation daily. In an effort to assist other new developers in navigating the docs more easily, I occasionally point out errors. However, if the entire documentation is set to be updated soon, I'd like your guidance. Should I primarily focus on coding contributions or continue to allocate some attention to documentation contributions as well? I would appreciate your approval on the best approach.

**Comment by stevepiercy** [comment]
@Vivek-04022001 please note that Training is a collection of trainings that are conducted in person at each Plone Conference every year (and sometimes for hire). Official Plone 6 Documentation is at https://6.docs.plone.org/. Many trainings refer to that as the authoritative source.

@ksuess refers to overhauling only the Mastering Plone training. Other trainers update their own trainings, usually about a month or two before the conference.

Corrections for errors and omission are welcome, as is feedback. However it better to file an issue, not a pull request, to discuss what should change, if anything. That saves everyone time and effort. See [Work with GitHub issues](https://6.docs.plone.org/contributing/first-time.html#work-with-github-issues).

**Comment by Vivek-04022001** [comment]
@ksuess, I'm reflecting on your suggestion to maintain all the terms mentioned in the docs. As a result, I propose a new change to you.

1.A page usually displays its blocks in the **default view**.
2.As a developer, you can create multiple views or modify the **default view**.
3.This is useful for adding **components** that should be shown, regardless of how an editor assembles a page with **blocks**.
4.By **default**, the **page** doesn't display its **contained** items but only the title and blocks created by an editor.
5.To reveal **contained** items, you can create a **listing block**.
6.If you use a l**isting block** without any specific criterias, it lists every **contained items**.

**Comment by ksuess** [comment]
Thanks @Vivek-04022001 . Integrating your feedback in training documentation: #910

**Pull request closed without merging**
