### PR TITLE
Some corrections and clarifications

### PR DESCRIPTION
**Pull request by jean**

### CODE REVIEW

**Comment by ebrehault** [comment]
@pbauer I would like to merge this PR, but we get a Travis error with openssl: https://travis-ci.org/plone/training/builds/162407577

Do you know what kind of problem is that ?

**Comment by pbauer** [comment]
The error does not say mean anything to me. I restarted the build and it failed again. But the same command `openssl aes-256-cbc -K $encrypted_129e1d4a0f4f_key -iv $encrypted_129e1d4a0f4f_iv -in deploy_key.enc -out $HOME/.ssh/id_rsa -d` seems to work in other branches without problems. Can you rebase?

**Comment by jean** [comment]
@ebrehault some more changes ... and still the same weird openssl error ...

**Comment by ebrehault** [comment]
@jean did you rebase as @pbauer said?

**Comment by pbauer** [comment]
I'll merge it now and if it fails in the master I'll ask @svx for help.

**Comment by pbauer** [comment]
It seems to have worked fine and is now deployed. Beats me 😕

**Pull request merged**
